version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-name: "*adevinta*"
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
