language: ruby
rvm:
  - 3.2.2
services:
  - docker
before_install:
  - yes | gem update --system --force
  - gem install bundler
script:
  - ./script/start-pg
  - ./script/test
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
