language: ruby
rvm:
  - 2.5.9
services:
  - docker
script:
  - ./script/testdb
  - ./script/test
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
