# Copyright 2021 Adevinta

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') || 6 %>
  timeout: <%= ENV['RAILS_DB_TIMEOUT'] || 10000 %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  port: <%= ENV.fetch('POSTGRES_PORT') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: <%= ENV.fetch('POSTGRES_DB') %>
  sslmode: <%= ENV.fetch('POSTGRES_SSLMODE','prefer') %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
