#!/bin/bash

# Copyright 2021 Adevinta

set -e 

docker run --name postgres -p 5432:5432 -e POSTGRES_USER=vulcan -e POSTGRES_PASSWORD=vulcan --rm -d postgres:13.3-alpine

while ! nc -z localhost 5432; do echo "Waiting for postgres" && sleep 2; done;
