#!/bin/bash

set -e

while ! nc -z localhost 5432; do echo "Waiting for postgres" && sleep 2; done;

RAILS_ENV=test bundle exec rake db:create
RAILS_ENV=test bundle exec rake db:migrate

bundle exec rake test
