#!/bin/bash

set -e

docker run --name postgres -p 5432:5432 -e POSTGRES_USER=vulcan -e POSTGRES_PASSWORD=vulcan --rm -d postgres:13.3-alpine

sleep 5

RAILS_ENV=development bundle exec rake db:reset
RAILS_ENV=test bundle exec rake db:reset
